FROM bitnami/spark:4.0.0

USER root

# Instala Java 17 y utilidades necesarias
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    openjdk-17-jdk-headless \
    procps \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Define JAVA_HOME para Spark
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH